// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWme9_ACJ_rQwSJ9OkHEGBNOgbmqUtcSA',
    appId: '1:877970525115:web:a183d7387dd25fe0c4929e',
    messagingSenderId: '877970525115',
    projectId: 'to-do-app-9c885',
    authDomain: 'to-do-app-9c885.firebaseapp.com',
    storageBucket: 'to-do-app-9c885.appspot.com',
    measurementId: 'G-03SZ8XSVHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXv2akAO34HRnKq5iEPfeTTYOoHcSi5TU',
    appId: '1:877970525115:android:5406d8ba2501a6ebc4929e',
    messagingSenderId: '877970525115',
    projectId: 'to-do-app-9c885',
    storageBucket: 'to-do-app-9c885.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVNds6_Lc4hm9wJS0dJRFERz5mT1SrpQM',
    appId: '1:877970525115:ios:7f5b5d734a117615c4929e',
    messagingSenderId: '877970525115',
    projectId: 'to-do-app-9c885',
    storageBucket: 'to-do-app-9c885.appspot.com',
    iosClientId: '877970525115-ppq5g46v1ss481b9lk1oid84buapt395.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVNds6_Lc4hm9wJS0dJRFERz5mT1SrpQM',
    appId: '1:877970525115:ios:7f5b5d734a117615c4929e',
    messagingSenderId: '877970525115',
    projectId: 'to-do-app-9c885',
    storageBucket: 'to-do-app-9c885.appspot.com',
    iosClientId: '877970525115-ppq5g46v1ss481b9lk1oid84buapt395.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppGetx',
  );
}
